# 1. definição de variáveis, matrizes e vetores

## 1.1 matrizes

In [2]:
import numpy as np
# uma variável escalar simples
a = 10
print(a, '\n')

b = np.array([1,2,3,4], dtype = np.float64)
print(b, '\n')

# acessar componente do vetor
print(b[2], '\n')

# matriz
c = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]], dtype = np.float64)
print(c, '\n')

# acessar componente da matriz
print(c[2,2], '\n')

# shape de uma matriz
print(c.shape, '\n')
print(c.shape[0]) #numero de linhas
print(c.shape[1]) #numero de colunas

10 

[1. 2. 3. 4.] 

3.0 

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

9.0 

(3, 3) 

3
3


## 1.2 matrizes especiais

In [9]:
# matrizes feita de zeros
Z = np.zeros(shape = (5,3), dtype = np.float64)
print(Z, '\n')

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 



In [10]:
# matriz feita de uns
U = np.ones(shape = (2,5), dtype = np.float64)
print(U, '\n')

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 



In [11]:
# matriz identidade
I = np.identity(4, dtype = np.float64)
print(I, '\n')

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 



In [19]:
# matrizes randômicas 
# números uniformemente distribuídos entre (0,1)
R = np.random.rand(3,4)
print(R, '\n')

# números uniformemente distribuídos entre (a,b)
a = 2.5
b = 3.8
U = np.ones(shape = (3,4), dtype = np.float64)
Q = a*U + (b-a)*R
print(Q, '\n')

# números randômicas inteiros [a,b) (a inclusivo e b não inclusivo)
Ui = np.random.randint(4,8, size=(6,2))
print(Ui, '\n')

[[0.26368489 0.02138616 0.42303183 0.74467665]
 [0.12120791 0.87705731 0.56603995 0.70967581]
 [0.32254614 0.15092113 0.63170508 0.3704409 ]] 

[[2.84279036 2.527802   3.04994138 3.46807965]
 [2.65757028 3.64017451 3.23585193 3.42257855]
 [2.91930998 2.69619747 3.3212166  2.98157317]] 

[[5 7]
 [6 5]
 [6 4]
 [5 5]
 [5 6]
 [4 7]] 



## 1.3 operações com matrizes e vetores

## 1.4 Aplicar uma função num array

In [23]:
CZ = np.cos(Z)
print(CZ, '\n')

EI = np.exp(I)
print(EI, '\n')

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[2.71828183 1.         1.         1.        ]
 [1.         2.71828183 1.         1.        ]
 [1.         1.         2.71828183 1.        ]
 [1.         1.         1.         2.71828183]] 



### 1.3.2 Slicing

In [27]:
vetor1 = EI[1,:]
print(vetor1, '\n')

vetor2 = EI[:,3]
print(vetor2, '\n')

vetor3 = EI[2:4,1]
print(vetor3, '\n')

vetor4 = np.diag(EI)
print(vetor4, '\n')

newmatrix = np.diag(vetor4)
print(newmatrix, '\n')

newmatriz = np.diag(np.diag(EI))
print(newmatrix)

[1.         2.71828183 1.         1.        ] 

[1.         1.         1.         2.71828183] 

[1. 1.] 

[2.71828183 2.71828183 2.71828183 2.71828183] 

[[2.71828183 0.         0.         0.        ]
 [0.         2.71828183 0.         0.        ]
 [0.         0.         2.71828183 0.        ]
 [0.         0.         0.         2.71828183]] 

[[2.71828183 0.         0.         0.        ]
 [0.         2.71828183 0.         0.        ]
 [0.         0.         2.71828183 0.        ]
 [0.         0.         0.         2.71828183]]


## 1.4 operações entre arrays

In [44]:
v1 = np.array([1.0, 2.0, 3.0], dtype = np.float64)
v2 = np.array([2.0, 3.0, 4.0], dtype = np.float64)

# combinação linear de vetores
alpha = 0.4
beta = 0.6
v3 = alpha*v1 + beta*v2
print(v3, '\n')

# produto ponto a ponto
v4 = v1 * v2
print(v4, '\n')

# produto escalar
p = v1 @ v2
print(p, '\n')

# seria o mesmo que fazer
q = np.sum(v4)
print(q, '\n')

# produto usual Matriz-vetor
A = np.array([[1,2,3], [4,5,6]], dtype = np.float64)
x = np.array([10,20,30])
y = A @ x
print(y, '\n')

[1.6 2.6 3.6] 

[ 2.  6. 12.] 

20.0 

20.0 

[140. 320.] 



## 1.4 estruturas de repetição

In [35]:
for i in range(6):
    print(i)
print('\n')
for i in range(3,10):
    print(i)

0
1
2
3
4
5


3
4
5
6
7
8
9


In [39]:
# Python range (start, stop, step)
for i in range(4,10,2):
    print(i)
print('\n')
a = 0
while(a<10):
    print(a)
    a += 3

4
6
8


0
3
6
9


In [43]:
for xi in x:
    print(xi)

print('\n\n')

for i,xi in enumerate(x):
    print(i,xi)

1
2
4



0 1
1 2
2 4


## 1.5 estruturas condicionais

In [46]:
a = np.random.rand()
if(a>0 and a<0.25):
    print('kksncn')
elif(a>= 0.25 and a <0.75):
    print('anjna')
else:
    print('nmmmm')

nmmmm


## 1.6 declaração de funções

In [4]:
def myfunc(A, B):
    ncA = A.shape[1]
    nlB = B.shape[0]
    if(ncA != nlB):
        raise Exception('Produto incompatível')
        
    nlA, ncB = A.shape[0], B.shape[1]
    C = np.zeros(shape = (nlA, ncB))

    for i in range(nlA):
        for j in range(ncB):
            for k in range(ncA):
                C[i,j] += A[i,k]*B[k,j]
    return C

In [5]:
m = 4
r= 4
n = 4

A = np.random.rand(m,r)
B = np.random.rand(r,n)

C = myfunc(A,B)

D = A @ B

dif = np.linalg.norm(D - C)
print(dif, '\n')
print(np.max(np.abs(dif)), '\n')
if(dif<0.0000000000000001 and dif > -0.0000000001):
    print('dif =', 0)
else:
    print('pois é... não deu certo')

3.8459253727671276e-16 

3.8459253727671276e-16 

pois é... não deu certo
